# This file was generated by GoReleaser. DO NOT EDIT.
cask "grimoire" do
  version "1.5.0"

  on_macos do
    on_arm do
      sha256 "c1a90c2241cbf8c965757f6fc687ccdba6129353c375a4db80b7446af5b9d670"
      url "https://github.com/JeremiahM37/grimoire/releases/download/v#{version}/grimoire_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f30dfcd5eacc9b177b2548e8d97aba6c1fc646e6bf802f172b8b278006ce84e6"
      url "https://github.com/JeremiahM37/grimoire/releases/download/v#{version}/grimoire_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bf4d358f4d963133df3517b7247cec2e4e0d165af98efe147be25a6677f7c6b1"
      url "https://github.com/JeremiahM37/grimoire/releases/download/v#{version}/grimoire_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "928de83fad32c3cfd29583dfbd55a73d78a6ef1b5be3c52c7143d53b73c23446"
      url "https://github.com/JeremiahM37/grimoire/releases/download/v#{version}/grimoire_linux_amd64.tar.gz"
    end
  end

  name "grimoire"
  desc "Personal knowledge base and agent memory server"
  homepage "https://github.com/JeremiahM37/grimoire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grimoire"
  binary "grimoire-mcp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grimoire"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grimoire-mcp"]
    end
  end

  # No zap stanza required
end
