# This file was generated by GoReleaser. DO NOT EDIT.
cask "grimoire" do
  version "1.10.0"

  on_macos do
    on_arm do
      sha256 "e90961115f013630b13bad981620b72fb9d89d4f7f60605279f90044586feb9c"
      url "https://github.com/JeremiahM37/grimoire/releases/download/v#{version}/grimoire_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8dc7d8f035d43f5caed0959c21c919be76edb7e04d7df9fb501151bfa80d12d9"
      url "https://github.com/JeremiahM37/grimoire/releases/download/v#{version}/grimoire_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c2e6cb2846887f888d829efa7b8ef226cb2c617bf5c5b2303a94ac9049db57c7"
      url "https://github.com/JeremiahM37/grimoire/releases/download/v#{version}/grimoire_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "de48ac1a395ccb6546b593cb82c8fb6a312930bf7fcb6b8badb8ae0c09528ad8"
      url "https://github.com/JeremiahM37/grimoire/releases/download/v#{version}/grimoire_linux_amd64.tar.gz"
    end
  end

  name "grimoire"
  desc "Personal knowledge base and agent memory server"
  homepage "https://github.com/JeremiahM37/grimoire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grimoire"
  binary "grimoire-mcp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grimoire"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grimoire-mcp"]
    end
  end

  # No zap stanza required
end
