# This file was generated by GoReleaser. DO NOT EDIT.
cask "grimoire" do
  version "1.8.1"

  on_macos do
    on_arm do
      sha256 "b326d3bd58b9c2f7b8c17cedfd13b3d46649da33ca6811242cc43809d997a7cd"
      url "https://github.com/JeremiahM37/grimoire/releases/download/v#{version}/grimoire_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "baca8e2de10bd27a9fb60fbe1a4b560720ac1cb6f50a64d59749bc30058e2922"
      url "https://github.com/JeremiahM37/grimoire/releases/download/v#{version}/grimoire_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7f7c106204a1867d4cc677488db98eb1550c5c10396ed23ce40af18355a2de64"
      url "https://github.com/JeremiahM37/grimoire/releases/download/v#{version}/grimoire_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bf5cddbbec9f503c2fad86981777cd42b30264cdaa6c7477691ae84b8920bcc4"
      url "https://github.com/JeremiahM37/grimoire/releases/download/v#{version}/grimoire_linux_amd64.tar.gz"
    end
  end

  name "grimoire"
  desc "Personal knowledge base and agent memory server"
  homepage "https://github.com/JeremiahM37/grimoire"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grimoire"
  binary "grimoire-mcp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grimoire"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grimoire-mcp"]
    end
  end

  # No zap stanza required
end
