# This file was generated by GoReleaser. DO NOT EDIT.
cask "lectern" do
  version "2.9.0"

  on_macos do
    on_arm do
      sha256 "26f008675fb313d068663f773d21381012fca7d42e5d5c8ede118190c2ff666e"
      url "https://github.com/JeremiahM37/lectern/releases/download/v#{version}/lectern_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9ef8161276c60afd0b667b1a3a1ec42b2da9aaa892cdf6aff6f9f88515ca296f"
      url "https://github.com/JeremiahM37/lectern/releases/download/v#{version}/lectern_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "262e1ec5ff2ee908b6450ec8bd003696c6ddd1cb5bfecb154a5036da79f24b69"
      url "https://github.com/JeremiahM37/lectern/releases/download/v#{version}/lectern_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "20993fb3d49c0d40add5848d3ea50beca9da9d875d64e017401da09e721cb7d5"
      url "https://github.com/JeremiahM37/lectern/releases/download/v#{version}/lectern_linux_amd64.tar.gz"
    end
  end

  name "lectern"
  desc "Mission control for AI coding agents on your own infrastructure"
  homepage "https://github.com/JeremiahM37/lectern"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "lectern"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lectern"]
    end
  end

  # No zap stanza required
end
