# This file was generated by GoReleaser. DO NOT EDIT.
cask "lectern" do
  version "2.10.0"

  on_macos do
    on_arm do
      sha256 "85e5c4bd25f2e7c62874167e2557a826fae8223fc088aad64ad185af8b6ba293"
      url "https://github.com/JeremiahM37/lectern/releases/download/v#{version}/lectern_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0ddf567ba934aafdd0057832c2397cd4484c20f77c351470702efa2519965bff"
      url "https://github.com/JeremiahM37/lectern/releases/download/v#{version}/lectern_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b74ea780b6e86bb357e0879dc53b33bcbfa377248eaf6735ad7a956d1129592d"
      url "https://github.com/JeremiahM37/lectern/releases/download/v#{version}/lectern_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7e93f5ee6f095a0fcc4314c8df6fe3a531306a6b05b40e338b9b676ed7083bd1"
      url "https://github.com/JeremiahM37/lectern/releases/download/v#{version}/lectern_linux_amd64.tar.gz"
    end
  end

  name "lectern"
  desc "Mission control for AI coding agents on your own infrastructure"
  homepage "https://github.com/JeremiahM37/lectern"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "lectern"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lectern"]
    end
  end

  # No zap stanza required
end
