# This file was generated by GoReleaser. DO NOT EDIT.
cask "lectern" do
  version "2.4.1"

  on_macos do
    on_arm do
      sha256 "ecb4a222b2b7e5a96e4721a96b7e895ec73d99cc0f26e8359dea811a536a52dc"
      url "https://github.com/JeremiahM37/lectern/releases/download/v#{version}/lectern_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "30d15628f495a4ddfe2957f8ee4752cd95f561f5523f758eeec841884bc28301"
      url "https://github.com/JeremiahM37/lectern/releases/download/v#{version}/lectern_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ce26389bcc3f2131471834028cf13e76ac5aa94863df39a6eee8523d6322d326"
      url "https://github.com/JeremiahM37/lectern/releases/download/v#{version}/lectern_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e32f122fadd5256f6d5866f7cd2f505551f510cae554aa7907d24470f0876b4f"
      url "https://github.com/JeremiahM37/lectern/releases/download/v#{version}/lectern_linux_amd64.tar.gz"
    end
  end

  name "lectern"
  desc "Mission control for AI coding agents on your own infrastructure"
  homepage "https://github.com/JeremiahM37/lectern"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "python",
      "tmux",
    ]

  binary "lectern"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lectern"]
    end
  end

  # No zap stanza required
end
